max_steps = 30 # 最大episode长度
[map]
width = 50 # 地图宽度
height = 50 # 地图高度
[team]
n_red_uav = 3 # 红方无人机数量
n_blue_uav = 3 # 蓝方无人机数量

[uav] # 无人机相关设置
hp = 10 # 生命值
fuel = 30 # 燃油量      
speed = 5 # 移速
missile_num  = 10 # 导弹数量
shoot_distance = 15 # 射击距离
visibility_range = 25 # 可见范围

[missile] # 导弹相关设置
damage_radius = 5 # 毁伤范围
damage = 3 # 最大伤害值

[RFUnit]
